# Generated by Django 2.2 on 2019-04-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_venda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
