# Generated by Django 2.2 on 2019-05-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_delete_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='doc',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
